server:
  port: 8080

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://123.206.28.162:3306/bbs?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: root


mybatis:
#    config_file: mybatis_config.xml
#    mapper_locations: /mapper/**.xml
#    entity_package: com.tcqc.bbs.entity

    mapper-locations: classpath:mapper/**.xml
    type-aliases-package: com.tcqc.bbs.entity